#!/usr/bin/env zsh
# =============================================================================
# aliases/laravel.sh — Laravel, PHP, and Composer aliases
# =============================================================================

# ---------------------------------------------------------------------------
# ARTISAN
# ---------------------------------------------------------------------------
alias art='php artisan'
alias pa='php artisan'
alias pas='php artisan serve'
alias pam='php artisan migrate'
alias pamf='php artisan migrate:fresh'
alias pamfs='php artisan migrate:fresh --seed'
alias pamr='php artisan migrate:rollback'
alias pams='php artisan migrate:status'
alias pamre='php artisan migrate:refresh'
alias pamres='php artisan migrate:refresh --seed'
alias pamt='php artisan migrate --env=testing'
alias pads='php artisan db:seed'
alias pads='php artisan db:seed'
alias padss='php artisan db:seed --class'
alias parcc='php artisan route:cache'
alias parcl='php artisan route:clear'
alias parl='php artisan route:list'
alias parca='php artisan route:cache'
alias pacc='php artisan config:cache'
alias paccl='php artisan config:clear'
alias pavc='php artisan view:cache'
alias pavcl='php artisan view:clear'
alias paevc='php artisan event:cache'
alias paevcl='php artisan event:clear'
alias paoc='php artisan optimize'
alias paocl='php artisan optimize:clear'
alias pacl='php artisan cache:clear'
alias paqlc='php artisan queue:clear'
alias paqr='php artisan queue:restart'
alias paqw='php artisan queue:work'
alias paqwt='php artisan queue:work --tries=3'
alias paqwq='php artisan queue:work --queue'
alias paqf='php artisan queue:failed'
alias paqfr='php artisan queue:retry all'
alias paqfl='php artisan queue:failed --json'
alias paqmon='php artisan queue:monitor'
alias pasched='php artisan schedule:run'
alias paschedl='php artisan schedule:list'
alias pask='php artisan schedule:work'
alias pacmk='php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear'

# Make commands
alias pamkm='php artisan make:model'
alias pamkmc='php artisan make:model --all'
alias pamkc='php artisan make:controller'
alias pamkrc='php artisan make:controller --resource'
alias pamkfc='php artisan make:controller --api'
alias pamks='php artisan make:service'
alias pamkr='php artisan make:request'
alias pamkmi='php artisan make:migration'
alias pamkseed='php artisan make:seeder'
alias pamkf='php artisan make:factory'
alias pamkp='php artisan make:policy'
alias pamkj='php artisan make:job'
alias pamke='php artisan make:event'
alias pamkl='php artisan make:listener'
alias pamkn='php artisan make:notification'
alias pamkmail='php artisan make:mail'
alias pamkch='php artisan make:channel'
alias pamkcmd='php artisan make:command'
alias pamkmid='php artisan make:middleware'
alias pamkobs='php artisan make:observer'
alias pamkrule='php artisan make:rule'
alias pamkres='php artisan make:resource'
alias pamkprov='php artisan make:provider'
alias pamkexc='php artisan make:exception'
alias pamktest='php artisan make:test'
alias pamku='php artisan make:test --unit'
alias pamkcast='php artisan make:cast'
alias pamkcomp='php artisan make:component'
alias pamksch='php artisan make:scope'

# Tinker
alias patink='php artisan tinker'
alias tin='php artisan tinker'

# Key
alias pakg='php artisan key:generate'

# Sail shortcuts (Laravel Sail)
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias sailu='sail up -d'
alias saild='sail down'
alias sailr='sail restart'
alias sailsh='sail shell'
alias sailba='sail bash'
alias sailart='sail artisan'
alias sailc='sail composer'
alias sailn='sail npm'
alias sailpn='sail pnpm'
alias sailmig='sail artisan migrate:fresh --seed'

# ---------------------------------------------------------------------------
# COMPOSER
# ---------------------------------------------------------------------------
alias c='composer'
alias ci='composer install'
alias cu='composer update'
alias cr='composer require'
alias crdev='composer require --dev'
alias crd='composer remove'
alias cda='composer dump-autoload'
alias cdao='composer dump-autoload --optimize'
alias cs='composer show'
alias cv='composer validate'
alias crun='composer run-script'
alias cdiag='composer diagnose'
alias cclr='composer clear-cache'
alias cself='composer self-update'
alias coutdated='composer outdated'
alias ccheck='composer check-platform-reqs'
alias cglobal='composer global'
alias cglobalr='composer global require'
alias cglobalshow='composer global show'

# ---------------------------------------------------------------------------
# PHP
# ---------------------------------------------------------------------------
alias php='php -d error_reporting=E_ALL'
alias phpv='php --version'
alias phpl='php --info | less'
alias phpconf='php --ini'
alias phperr='php --display_errors=1'
alias phptest='php -r'
alias phpstan='vendor/bin/phpstan'
alias pstan='vendor/bin/phpstan analyse'
alias phpcs='vendor/bin/phpcs'
alias phpcbf='vendor/bin/phpcbf'
alias pint='vendor/bin/pint'
alias pest='vendor/bin/pest'
alias phpunit='vendor/bin/phpunit'
alias pu='vendor/bin/phpunit'
alias puf='vendor/bin/phpunit --filter'
alias pug='vendor/bin/phpunit --group'
alias puc='vendor/bin/phpunit --coverage-html coverage'
alias psect='vendor/bin/pest --parallel'

# ---------------------------------------------------------------------------
# LARAVEL-SPECIFIC QUICK COMMANDS
# ---------------------------------------------------------------------------
alias fresh='php artisan migrate:fresh --seed && echo "Database refreshed!"'
alias serve='php artisan serve'
alias tink='php artisan tinker'
alias logs='tail -f storage/logs/laravel.log'
alias envcp='cp .env.example .env && php artisan key:generate'
alias larainstall='composer install && cp .env.example .env && php artisan key:generate && php artisan migrate:fresh --seed'
